- name: Ensuring pkgs for tftp are installed
  yum:
    name: ['tftp', 'tftp-server', 'syslinux-tftpboot', 'syslinux-extlinux']
    state: installed
  register: tftp_init

- name: Importing tftpboot syslinux files
  copy:
    remote_src: yes
    src: "/tftpboot/"
    dest: /var/lib/tftpboot/
  when: tftp_init is changed and ansible_distribution_major_version == '8'

- name: tftpboot directory structure
  file:
    path: "/var/lib/tftpboot/{{ item }}"
    state: directory
  with_items:
    - pxelinux.cfg
    - boot

- name: pxelinux default menu
  template:
    src: templates/pxelinux_default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    mode: 0644
  tags:
    - config

- name: pxelinux EFI default menu
  template:
    src: templates/grub_default.j2
    dest: /var/lib/tftpboot/grub.cfg
    mode: 0644
  tags:
    - config
    - efi

- name: Downloading required EFI boot files
  get_url:
    url: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items: "{{ boot_pxe_source_files }}"
  tags:
    - efi

- name: Opening up iptables for tftpd
  include_role:
    name: iptables
    tasks_from: custom-policy
  vars:
    iptables_policy_name: tftpd
    iptables_protocol: udp
    iptables_port: "69"
  tags:
    - iptables

- name: tftpd is started
  service: 
    name: tftp
    state: started
    enabled: True

- name: Script to fetch kernel/initrd pxe images
  template:
    src: pxefetch.j2
    dest: /usr/libexec/centos/pxefetch
    mode: 0750
  notify:
    - pxe_fetch_files

- name: Refreshing install artifacts (kernel/initrd)
  cron:
    name: refresh pxe artifacts
    minute: '5'
    job: /usr/libexec/centos/pxefetch
  tags:
    - cron
